In [12]:
# Cargar variables del archivo .env
from dotenv import load_dotenv
load_dotenv()

import os
from hf_dataset_loader import HFDatasetLoader
from dataset_summarizer import DatasetSummarizer

# Verificar que el token esté cargado
token = os.environ.get("HF_TOKEN")
if token:
    print(f"✅ Token configurado: {token[:10]}...")
else:
    print(" ERROR: HF_TOKEN no está configurado. Revisa el archivo .env")

✅ Token configurado: hf_uMnnRbo...

In [13]:
# Usamos scikit-learn/iris
loader = HFDatasetLoader("scikit-learn/iris", split="train")
df = loader.load()

print(f"✅ Dataset cargado: {df.shape[0]} filas, {df.shape[1]} columnas")
print(f"Columnas originales: {list(df.columns)}")
df.head(10)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

✅ Dataset cargado: 150 filas, 6 columnas
Columnas originales: ['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species']

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa
6   7            4.6           3.4            1.4           0.3  Iris-setosa
7   8            5.0           3.4            1.5           0.2  Iris-setosa
8   9            4.4           2.9            1.4           0.2  Iris-setosa
9  10            4.9           3.1            1.5           0.1  Iris-setosa

In [ ]:
# Renombrar columnas 
df = df.rename(columns={
    "SepalLengthCm": "longitud_sepalo",
    "SepalWidthCm": "ancho_sepalo",
    "PetalLengthCm": "longitud_petalo",
    "PetalWidthCm": "ancho_petalo",
    "Species": "especie"
})

print("✅ Transformación 1: Renombrar columnas")
print(f"Columnas después: {list(df.columns)}")
df.head()

✅ Transformación 1: Renombrar columnas
Columnas después: ['Id', 'longitud_sepalo', 'ancho_sepalo', 'longitud_petalo', 'ancho_petalo', 'especie']

,Id,longitud_sepalo,ancho_sepalo,longitud_petalo,ancho_petalo,especie
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa

In [17]:
# Crear columna que calcula el ratio entre longitud y ancho del sépalo
df["ratio_sepalo"] = df["longitud_sepalo"] / df["ancho_sepalo"]

print("✅ Transformación 2: Crear columna 'ratio_sepalo'")
print(f"Estadísticas de ratio_sepalo:\n{df['ratio_sepalo'].describe()}")
df[["longitud_sepalo", "ancho_sepalo", "ratio_sepalo"]].head(10)

✅ Transformación 2: Crear columna 'ratio_sepalo'
Estadísticas de ratio_sepalo:
count    150.000000
mean       1.955144
std        0.398697
min        1.268293
25%        1.551915
50%        2.032292
75%        2.224910
max        2.961538
Name: ratio_sepalo, dtype: float64

   longitud_sepalo  ancho_sepalo  ratio_sepalo
0              5.1           3.5      1.457143
1              4.9           3.0      1.633333
2              4.7           3.2      1.468750
3              4.6           3.1      1.483871
4              5.0           3.6      1.388889
5              5.4           3.9      1.384615
6              4.6           3.4      1.352941
7              5.0           3.4      1.470588
8              4.4           2.9      1.517241
9              4.9           3.1      1.580645

In [18]:
# Filtrar solo flores con ratio_sepalo mayor a 1.5
df_filtrado = df[df["ratio_sepalo"] > 1.5].copy()

print(f"✅ Transformación 3: Filtrar ratio_sepalo > 1.5")
print(f"Filas antes: {df.shape[0]} → Filas después: {df_filtrado.shape[0]}")
df_filtrado.head()

✅ Transformación 3: Filtrar ratio_sepalo > 1.5
Filas antes: 150 → Filas después: 118

,Id,longitud_sepalo,ancho_sepalo,longitud_petalo,ancho_petalo,especie,ratio_sepalo
1,2,4.9,3.0,1.4,0.2,Iris-setosa,1.633333
8,9,4.4,2.9,1.4,0.2,Iris-setosa,1.517241
9,10,4.9,3.1,1.5,0.1,Iris-setosa,1.580645
12,13,4.8,3.0,1.4,0.1,Iris-setosa,1.600000
18,19,5.7,3.8,1.7,0.3,Iris-setosa,1.500000

In [19]:
# Seleccionar solo las columnas más relevantes
columnas_relevantes = [
    "longitud_sepalo", "ancho_sepalo", "ratio_sepalo", "especie"
]

df_final = df_filtrado[columnas_relevantes].copy()

print("✅ Transformación 4: Seleccionar columnas relevantes")
print(f"Columnas finales: {list(df_final.columns)}")
print(f"Dataset final: {df_final.shape[0]} filas, {df_final.shape[1]} columnas")
df_final.head(10)

✅ Transformación 4: Seleccionar columnas relevantes
Columnas finales: ['longitud_sepalo', 'ancho_sepalo', 'ratio_sepalo', 'especie']
Dataset final: 118 filas, 4 columnas

    longitud_sepalo  ancho_sepalo  ratio_sepalo      especie
1               4.9           3.0      1.633333  Iris-setosa
8               4.4           2.9      1.517241  Iris-setosa
9               4.9           3.1      1.580645  Iris-setosa
12              4.8           3.0      1.600000  Iris-setosa
18              5.7           3.8      1.500000  Iris-setosa
20              5.4           3.4      1.588235  Iris-setosa
23              5.1           3.3      1.545455  Iris-setosa
25              5.0           3.0      1.666667  Iris-setosa
28              5.2           3.4      1.529412  Iris-setosa
30              4.8           3.1      1.548387  Iris-setosa

In [20]:
summarizer = DatasetSummarizer(df_final, title="Resumen Dataset Iris - Transformado")
ruta = summarizer.save_txt("resumen_dataset.txt")
print(f"✅ Resumen guardado en: {ruta}")

✅ Resumen guardado en: resumen_dataset.txt

In [21]:
with open("resumen_dataset.txt", "r", encoding="utf-8") as f:
    print(f.read())

Resumen Dataset Iris - Transformado
===================================
Filas: 118
Columnas: 4

Columnas y tipos de datos:
  - longitud_sepalo: float64
  - ancho_sepalo: float64
  - ratio_sepalo: float64
  - especie: str

Valores nulos por columna:
  - longitud_sepalo: 0
  - ancho_sepalo: 0
  - ratio_sepalo: 0
  - especie: 0
Total de nulos: 0

Estadísticas descriptivas:
        longitud_sepalo  ancho_sepalo  ratio_sepalo          especie
count        118.000000    118.000000    118.000000              118
unique              NaN           NaN           NaN                3
top                 NaN           NaN           NaN  Iris-versicolor
freq                NaN           NaN           NaN               50
mean           6.071186      2.916102      2.103451              NaN
std            0.769293      0.344671      0.312004              NaN
min            4.400000      2.000000      1.500000              NaN
25%            5.600000      2.700000      1.957391              NaN
50%            6.100000      3.000000      2.148148              NaN
75%            6.575000      3.100000      2.250000              NaN
max            7.900000      3.800000      2.961538              NaN